apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ml2vuv6i2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ml2vuv6i2-go 
  name: ml2vuv6i2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ml2vuv6i2-go 
